apiVersion: v1
kind: ServiceAccount
metadata:
  name: pre-install-{{ template "name" . }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.labels }}
  labels:
    {{ toYaml .Values.labels }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
