apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pre-install-{{ template "name" . }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.labels }}
  labels:
    {{ toYaml .Values.labels }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - delete
