apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pre-install-{{ template "name" . }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.labels }}
  labels:
    {{ toYaml .Values.labels }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: pre-install-{{ template "name" . }}
    namespace: {{ .Values.namespace | quote }}
roleRef:
  kind: Role
  name: pre-install-{{ template "name" . }}
  apiGroup: rbac.authorization.k8s.io
