global:
  domain: mukta.odisha.gov.in
  tracing-enabled: true
  setup: fullsetup

cluster-configs:
  namespaces:
    create: true
    values:
      [
        backbone,
        cert-manager,
        es-cluster,
        kafka-cluster,
        logging,
        monitoring,
        playground,
        zookeeper-cluster,
        ifix
      ]

  root-ingress:
    cert-issuer: letsencrypt-prod

  secrets:
    db:
      namespace: [ ifix ]
      name: db
    program-service:
      namespace: [ ifix, works ]
      name: program-service

  configmaps:
    egov-config:
      namespace: [ ifix, monitoring ]
      data:
        db-host: "mukta-prod-db.csju60oewij7.ap-south-1.rds.amazonaws.com"
        db-name: "mukta_prod_db"
        db-url: "jdbc:postgresql://mukta-prod-db.csju60oewij7.ap-south-1.rds.amazonaws.com:5432/mukta_prod_db"
        ifix-db-url: "jdbc:postgresql://mukta-prod-db.csju60oewij7.ap-south-1.rds.amazonaws.com:5432/mukta_prod_db?currentSchema=ifix"
        domain: "https://mukta.odisha.gov.in"
        egov-services-fqdn-name: "https://mukta.odisha.gov.in/"
        egov-state-level-tenant-id: "od"
        es-host: "elasticsearch-data-v8.es-upgrade"
        es-indexer-host: "http://elasticsearch-data-v8.es-upgrade:9200/"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/master"
        kafka-brokers: "kafka-v2.kafka-cluster:9092"
        kafka-infra-brokers: "kafka-v2-infra.kafka-cluster:9092"
        logging-level-jdbc: "debug"
        mobile-validation-workaround: "true"
        s3-assets-bucket: "(mukta-prod-s3)"
        serializers-timezone-in-ist: "true"
        server-tomcat-max-threads: "10"
        server-tomcat-max-connections: "500"
        sms-enabled: "true"
        spring-datasource-tomcat-initialSize: "1"
        spring-datasource-tomcat-max-active: "2"
        spring-jpa-show-sql: "true"
        tracer-errors-provideexceptionindetails: "true"
        timezone: "Asia/Kolkata"
        es-infra-host: elasticsearch-data-v8.es-upgrade
        db-ssl: "false"
        state-level-tenant-id: "od"
        sms-isAdditonalFieldRequired: true
        parent-level-tenant-id: "od"

    egov-service-host:
      namespace: [ ifix, monitoring ]
      data:
        egov-mdms-service: "http://egov-mdms-service.egov:8080/"
        egov-enc-service: "http://egov-enc-service.egov:8080/"
        egov-user: "http://egov-user.egov:8080/"
        egov-location: "http://egov-location.egov:8080/"
        egov-accesscontrol: "http://egov-accesscontrol.egov:8080/"
        egov-localization: "http://egov-localization.egov:8080/"
        egov-filestore: "http://egov-filestore.egov:8080/"
        egov-idgen: "http://egov-idgen.egov:8080/"
        egov-workflow-v2: "http://egov-workflow-v2.egov:8080/"

        attendance-service: "http://attendance.works:8080/"
        contract-service: "http://contracts.works:8080/"
        muster-roll-service: "http://muster-roll.works:8080/"
        project-management-system: "http://project.works:8080/"
        estimate-service: "http://estimates.works:8080/"
        organisation: "http://organisation.works:8080/"
        bankaccounts: "http://bankaccounts.works:8080/"
        expense-calculator: "http://expense-calculator.works:8080/"
        expense: "http://expense.works:8080/"
        works-management-service: "http://works-management-service.works:8080/"
        individual: "http://individual.works:8080/"
        works-pdf: "http://works-pdf.works:8080/"
        ifms-jit: "https://www.odishatreasury.gov.in"
        ifms-adapter: "http://ifms-adapter.works:8080/"

        audit-service: "http://audit-service.egov:8080/"
        dashboard-analytics: http://dashboard-analytics.egov:8080/
        dashboard-ingest: http://dashboard-ingest.egov:8080/
        data-sync-employee: "http://data-sync-employee:8080/"
        egov-common-masters: "http://egov-common-masters:8080/"
        egov-user-egov: "http://egov-user.egov:8080/"
        egov-otp: "http://egov-otp:8080/"
        minio-url: "http://minio.backbone:9000/"
        egov-common-workflows: "http://egov-common-workflows:8080/"
        egov-workflow: "http://egov-workflow:8080/"
        egov-searcher: "http://egov-searcher.egov:8080/"
        egov-indexer: "http://egov-indexer.egov:8080/"
        egov-hrms: "http://egov-hrms.egov:8080/"
        location: "http://location:8080/"
        pdf-service: "http://pdf-service.egov:8080/"
        user-otp: "http://user-otp:8080/"
        zuul: "http://zuul:8080/"
        egov-url-shortening: "http://egov-url-shortening.egov:8080/"
        inbox: "http://inbox.egov:8080/"
        egov-pdf: "http://egov-pdf.egov:8080/"
        es-client: http://elasticsearch-data-v8.es-upgrade:9200
        es-client-infra: http://elasticsearch-data-infra-v1.es-cluster-infra:9200
        measurement: "http://measurement-service.works:8080/"

        measurement-service: "http://measurement-service.works:8080/"
        measurement-registry: "http://measurement-registry.works:8080/"
        egov-mdms-service-v2: "http://mdms-v2.egov:8080/"
        bulk-upload: "http://bulk-upload.egov:8080/"
        mukta-services: "http://mukta-services.works:8080/"

        digit-exchange: "http://digit-exchange.ifix:8080/"
        program-service: "http://program-service.ifix:8080/"
        ifix-adapter: "http://ifix-adapter.works:8080/"

digit-exchange:
  tracing-enabled: true
  java-enable-debug: true
  app-enable-events-log: true
  app-auth-sign-validation: true
  app-auth-private-key: "-----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4HGQPToO6knBfwxIS8H/GC6Msk4dmjxGxJSQ0W/J9uTn7wWg6bgLtdcKt4JZW1QH6fou8HcXvbA/lbtPhJ3u4C+QmHlDWIAd6YPpG//kq5pwR4ccyWAYdR5c20ejw9TG1/EKLzS6wcELYOdxcDWbbIbGoIf22a3k7Qju9QVaKtwvW8S5VZFLW/iwHocGl1q5VcxFESDSFkyr9vYxbihRFZCFJUBVZjJfZL/0OHV2YL9i0ENw/MAh3IoAAEarXzpL6M6foUhtlYo65K3gtZYemu4tvll50yMrQDrI5oFR38zpj3o1q68C5kx6L2O0yQDc5amYiNlybCDnqzRSOlgyLAgMBAAECggEABe1VY/rCmeM0qUM7QI8r2zaCXSEuEZAB4U0796WNeR0D8AYUyBYaPlvKqyoDnQMEKnTKzyu5ihDVXYJZDDK8XxCe79fiVqphoz/I/uJ8ZTRXCj+rAoS77v21hrHGSS+Tl0i/jwb0KFZM3e+AQm8PWcxMDwjHxV4mC9GA4Sxf0Aew5aB1ZRgvLbjeu0LcuYPzAM49CDQqeb/p43G8dMHgiWhg4ldf9Zd1y+/Hi9zuYgiFqqFNoGbJgb31KNcBuZifQYIJNCOCi8qiWZteCNxxLcrgGDIkPzIqW7f9nmRCPr+DVaeA7fwUkxId4RvhQIodgPhmJkFNx9kMr26ED1r6RQKBgQDhkHsXRBZz5pQSwpxp7HD1NXZZxbrvo0mUeuxPNFTb8q8xTJdOkzpjj0zM/14IGGZqaHeFAZ51yS5sIl3kGGJqi0Kpi/kSIc8P1kk+Ak+G6SvB9ECeoNJ+/WWiF3b3MCgFUlFBU31vWQGx6sUmR+YzoN7sPjm5l/x5/XhIHhLbNwKBgQDQ9AKn6rWkJIXKD7PJNYDrpqQ4rzQ6CNhx7M9Zm30jDfraQvG6TSLGc3n4gjOvqBUE/0L/tjU6CiITfHN1yJTsvX3cJJFVjFDYLlQlJjw9Qkwden9Vk7mZ4Gj006bE9jQ7/BMkO98DHfOH8Wk8LUO+V74eoHLQdEs0aZiQ61dLTQKBgHJnrYbnadvvHztEqcCvw7sbGqP9vgq9bxx4HFMv37qPJHyEtFmOIxdMH0/6Vd8VQRzHT5eOcqibGYiPBcAi/ge8ClukOvgPXc5SiWOCGIP8z8zX7c6HEzyFmX7VF+nX6vSIA952UjCfnFR5FvWLkh6tgWOhS/XuOIhHHzK0ziuRAoGBAKYGjCmx05vVrTxtF5QzX/ld0jR7+cp3BswWtnZjlp2I2R4dfQZjjdMTJAHyKnFS40iyLiESPN6d+I91HiSjOLmWou+NWrEXqZDr1s4hwFGIYQQ3Nf/gPePnLF4D4gmz+rMCyo7Kx5spbDxC9DPtX1tZSmX5ZOD+1laR5LiZViYtAoGAGijlsYiCZf2YFModVwxin8GIvMhD/LloQTWoMS2ja9l7kmGO5Jtc/NimuDgPwYIIjjKthwZYCx1PTiU5MO99cB9VOE5Ktzv35V8i8LA6mV2RnqPCTC/5pxbaQTO0oWRc9AN+ciNtbZxn9BqwAdTXNTW443qXD0vjILXRpDYpYiE=-----END PRIVATE KEY-----"
  app-auth-public-key: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuBxkD06DupJwX8MSEvB/xgujLJOHZo8RsSUkNFvyfbk5+8FoOm4C7XXCreCWVtUB+n6LvB3F72wP5W7T4Sd7uAvkJh5Q1iAHemD6Rv/5KuacEeHHMlgGHUeXNtHo8PUxtfxCi80usHBC2DncXA1m2yGxqCH9tmt5O0I7vUFWircL1vEuVWRS1v4sB6HBpdauVXMRREg0hZMq/b2MW4oURWQhSVAVWYyX2S/9Dh1dmC/YtBDcPzAIdyKAABGq186S+jOn6FIbZWKOuSt4LWWHpruLb5ZedMjK0A6yOaBUd/M6Y96NauvAuZMei9jtMkA3OWpmIjZcmwg56s0UjpYMiwIDAQAB-----END PUBLIC KEY-----"
  app-receiver-endpoints: '{"program":"http://program-service.ifix:8080/ifms/program-service/v1/"}'
  service-host-url: "https://mukta.odisha.gov.in/ifms/digit-exchange"
  app-exchange-topic-name: "ifix-dx-exchange-topic"
  app-error-topic-name: "ifix-dx-exchange-error-queue"
  app-events-log-topic-name: "ifix-dx-exchange-event-log-queue"

program-service:
  tracing-enabled: true
  java-enable-debug: true
  heap: "-Xmx256m -Xms256m"
  memory_limits: 512Mi
  egov-idgen-idname: "ifix.program.number"
  adapter-host: "http://ifms-adapter.works:8080/"
  adapter-path: "ifms-adapter/v1/"
  search-default-limit: 20
  is-program-async: true
  is-sanction-async: false
  is-allocation-async: false
  is-disburse-async: true
  exchange-path: "ifms/digit-exchange/v1/exchange/"
  exchange-service-external-url: "https://mukta.odisha.gov.in/ifms/digit-exchange"
  program-kafka-topic: "ifix-ps-program-kafka-topic"
  sanction-kafka-topic: "ifix-ps-sanction-kafka-topic"
  allocation-kafka-topic: "ifix-ps-allocation-kafka-topic"
  disburse-kafka-topic: "ifix-ps-disburse-kafka-topic"
  error-queue: "ifix-ps-error-queue"