{{- with index .Values "cluster-configs" "secrets" "elasticsearch" }}
{{- if index . "password" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  username: {{ index .username | b64enc | quote }}
  password: {{ index .password | b64enc | quote }}
{{- end }}
{{- end }}
