{{- with index .Values "cluster-configs" "secrets" "elasticsearch-infra-certificate" }}
{{- if and .caCrt .tlsCrt .tlsKey }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "elasticsearch-infra-certificate" "name" }}
  namespace: {{ $ns }}
type: kubernetes.io/tls
data:
  ca.crt: {{ index $.Values "cluster-configs" "secrets" "elasticsearch-infra-certificate" "caCrt" | quote }}
  tls.crt: {{ index $.Values "cluster-configs" "secrets" "elasticsearch-infra-certificate" "tlsCrt" | quote }}
  tls.key: {{ index $.Values "cluster-configs" "secrets" "elasticsearch-infra-certificate" "tlsKey" | quote }}
---
{{- end }}
{{- end }}
{{- end }}
