# Common Labels
labels:
  app: "kibana-v8"
namespace: es-upgrade

# Ingress Configs
ingress:
  enabled: true
  context: "kibana-v8"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "docker.elastic.co/kibana/kibana"
  tag: 8.11.3
replicas: "1"
httpPort: 5601
elasticsearchHosts: "http://elasticsearch-data-v8.es-upgrade:9200"
elasticsearchCertificateSecret: elasticsearch-certs
elasticsearchCertificateAuthoritiesFile: ca.crt
elasticsearchCredentialSecret: elasticsearch-credentials
homeDir: "/usr/share/kibana"
serverBasePath: "/kibana-v8"
healthCheckPath: "kibana-v8/app/kibana"
healthChecks:
  enabled: true
  livenessProbePath: "/kibana-v8/"
  readinessProbePath: "/kibana-v8/"            

# Additional Container Envs
env: |
  - name: ELASTICSEARCH_HOSTS
    value: {{ .Values.elasticsearchHosts | quote }}
  - name: SERVER_BASEPATH
    value: {{ .Values.serverBasePath | quote }}
  - name: SERVER_REWRITEBASEPATH
    value: "true"
  - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
    value: "{{ .Values.homeDir }}/config/certs/{{ .Values.elasticsearchCertificateAuthoritiesFile }}"

extraVolumes: |
  - name: kibana-tokens
    emptyDir: {}
  - name: elasticsearch-certs
    secret:
      secretName: {{ .Values.elasticsearchCertificateSecret }}

extraVolumeMounts: |
  - name: elasticsearch-certs
    mountPath: {{ .Values.homeDir }}/config/certs
    readOnly: true
  - name: kibana-tokens
    mountPath: {{ .Values.homeDir }}/config/tokens
    readOnly: true