# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used

        # PROD environment ------------------------------------------------------------------------------------------------------------- #
        - kms: "arn:aws:kms:ap-south-1:611316314659:key/df40d050-3009-4bd8-9d2e-dd70de38ecad"
          encrypted_regex: '^(secrets)$'
          path_regex: 'mukta-prod-.*\.yaml'

        # UAT environment ------------------------------------------------------------------------------------------------------------- #
        - kms: "arn:aws:kms:ap-south-1:880678429748:key/fb845d89-ce3e-433f-91b6-a5fb96fee4df"
          encrypted_regex: '^(secrets)$'
          path_regex: 'mukta-uat-.*\.yaml'


