# Common Labels
labels:
  app: "boundary-migration"
  group: "rainmaker"

namespace: egov

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "boundary-migration"


# Container Configs
image:
  repository: "boundary-migration"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: SERVER_PORT
    value: "8080" 
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"      


